In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [5]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [6]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [7]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()
df

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,20000.0,17.19%,499.10,RENT,47000.0,Source Verified,Mar-2019,Issued,n,14.02,...,98.0,12.5,0.0,0.0,75824.0,31546.0,33800.0,21524.0,N,N
1,21225.0,14.74%,502.05,MORTGAGE,225000.0,Not Verified,Mar-2019,Issued,n,16.80,...,100.0,50.0,1.0,0.0,747075.0,209426.0,53500.0,128175.0,N,N
2,5000.0,17.97%,180.69,MORTGAGE,62000.0,Not Verified,Mar-2019,Issued,n,19.82,...,66.7,50.0,0.0,0.0,255738.0,31615.0,9400.0,39938.0,N,N
3,20000.0,8.19%,628.49,MORTGAGE,200000.0,Not Verified,Mar-2019,Issued,n,22.66,...,95.7,22.2,0.0,0.0,448069.0,84744.0,49400.0,105180.0,N,N
4,12000.0,15.57%,289.09,MORTGAGE,49000.0,Source Verified,Mar-2019,Issued,n,13.47,...,86.1,14.3,0.0,0.0,189260.0,106025.0,24400.0,68860.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115670,5000.0,13.56%,169.83,MORTGAGE,48000.0,Not Verified,Jan-2019,Current,n,8.28,...,90.5,NaN,0.0,0.0,88613.0,9182.0,0.0,11413.0,N,N
115671,6000.0,6.46%,183.79,MORTGAGE,96000.0,Not Verified,Jan-2019,Current,n,0.31,...,100.0,0.0,1.0,0.0,33500.0,50.0,14900.0,0.0,N,N
115672,16000.0,16.14%,563.62,MORTGAGE,32000.0,Source Verified,Jan-2019,Current,n,20.89,...,93.3,37.5,1.0,0.0,34200.0,17066.0,16400.0,0.0,N,N
115673,16000.0,11.31%,350.36,MORTGAGE,72000.0,Verified,Jan-2019,Current,n,7.02,...,94.3,0.0,1.0,0.0,251486.0,74835.0,23000.0,63090.0,N,N
115674,29250.0,18.94%,757.80,MORTGAGE,65000.0,Verified,Jan-2019,Current,n,29.52,...,100.0,76.9,0.0,0.0,237833.0,58788.0,38800.0,25728.0,N,N

In [8]:
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100

# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [5]:
# Load the data
# file_path = Path('LoanStats_2019Q1.csv.zip')
# df = pd.read_csv(file_path, skiprows=1)[:-2]
# df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
# df = df.dropna(axis='columns', how='all')

# Drop the null rows
# df = df.dropna()

# # Remove the `Issued` loan status
# issued_mask = df['loan_status'] != 'Issued'
# df = df.loc[issued_mask]

# # convert interest rate to numerical
# df['int_rate'] = df['int_rate'].str.replace('%', '')
# df['int_rate'] = df['int_rate'].astype('float') / 100


# # Convert the target column values to low_risk and high_risk based on their values
# x = {'Current': 'low_risk'}   
# df = df.replace(x)

# x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
# df = df.replace(x)

# df.reset_index(inplace=True, drop=True)

# df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [9]:
# Create our features
X= df.copy()
X = X.drop(columns=["loan_status"], axis=1)
X = pd.get_dummies(X, columns=["home_ownership","verification_status","issue_d","application_type","initial_list_status","next_pymnt_d","pymnt_plan","hardship_flag", "debt_settlement_flag"])
X

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,application_type_Individual,application_type_Joint App,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,pymnt_plan_n,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,0,1,0,1,1,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,0,1,0,1,1,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,0,1,0,1,1,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,0,1,0,1,1,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68812,10000.0,0.1502,346.76,26000.0,9.60,0.0,0.0,9.0,0.0,2684.0,...,0,1,0,0,1,0,1,1,1,1
68813,12000.0,0.2727,368.37,63000.0,29.07,0.0,0.0,8.0,0.0,13314.0,...,0,1,0,0,1,0,1,1,1,1
68814,5000.0,0.1992,185.62,52000.0,14.86,0.0,0.0,5.0,1.0,3715.0,...,0,1,0,0,1,0,1,1,1,1
68815,40000.0,0.0646,1225.24,520000.0,9.96,0.0,1.0,21.0,0.0,59529.0,...,0,1,0,1,0,0,1,1,1,1
68816,16000.0,0.1131,350.36,72000.0,7.02,2.0,0.0,12.0,1.0,11882.0,...,0,1,0,0,1,0,1,1,1,1

In [10]:
# Create our target
y=df["loan_status"]
y

0        low_risk
1        low_risk
2        low_risk
3        low_risk
4        low_risk
           ...
68812    low_risk
68813    low_risk
68814    low_risk
68815    low_risk
68816    low_risk
Name: loan_status, Length: 68817, dtype: object

In [11]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,application_type_Individual,application_type_Joint App,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,pymnt_plan_n,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,0.860340,0.139660,0.123879,0.876121,0.383161,0.616839,1.0,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.346637,0.346637,0.329446,0.329446,0.486161,0.486161,0.0,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.0,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.0,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0

# Split the Data into Training and Testing

In [6]:
# Create our features
X = # YOUR CODE HERE

# Create our target
y = # YOUR CODE HERE

In [7]:
# X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [12]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [8]:
# Check the balance of our target values
# y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# YOUR CODE HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# scaler = StandardScaler()
# scaler = scaler.fit(X_train)
# X_train_scaled = scaler.transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [14]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE

from imblearn.ensemble import BalancedRandomForestClassifier

clf = BalancedRandomForestClassifier(random_state=1, n_estimators=100).fit(X_train, y_train)

In [16]:
# predict X_test data
y_pred = clf.predict(X_test)

In [17]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.7731689767433245

In [18]:
# Display the confusion matrix
# YOUR CODE HERE

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[   68,    33],
       [ 2171, 14933]], dtype=int64)

In [19]:
# Print the imbalanced classification report
# YOUR CODE HERE

from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.67      0.87      0.06      0.77      0.58       101
   low_risk       1.00      0.87      0.67      0.93      0.77      0.60     17104

avg / total       0.99      0.87      0.67      0.93      0.77      0.60     17205

In [20]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
from matplotlib import pyplot as plt
# Calculate feature importance in the Random Forest model.
importances = clf.feature_importances_
# print(importances)

features = sorted(zip(X.columns, clf.feature_importances_), key = lambda x: x[1])

# cols = [f[0] for f in features]
# width = [f[1] for f in features]
# features.sorted(key=0, reverse=False)
# feature1= sorted(features, key=lambda x: x[1])
# feature1

features
               
    
    
# features[3][0]


# features.sort_values(ascending=False)
# features.sort(features[1])
# list(cols), list(width)

# print(f"{cols} :({width})")

# fig, ax = plt.subplots()

# fig.set_size_inches(10,200)
# plt.margins(y=0.001)

# ax.barh(y=cols, width=width)

# plt.show()

[('recoveries', 0.0),
 ('collection_recovery_fee', 0.0),
 ('policy_code', 0.0),
 ('acc_now_delinq', 0.0),
 ('delinq_amnt', 0.0),
 ('num_tl_120dpd_2m', 0.0),
 ('num_tl_30dpd', 0.0),
 ('tax_liens', 0.0),
 ('pymnt_plan_n', 0.0),
 ('hardship_flag_N', 0.0),
 ('debt_settlement_flag_N', 0.0),
 ('chargeoff_within_12_mths', 7.453067160232683e-05),
 ('home_ownership_ANY', 0.0004935536864290002),
 ('collections_12_mths_ex_med', 0.0008034508064424821),
 ('num_tl_90g_dpd_24m', 0.0009765214756222286),
 ('verification_status_Source Verified', 0.0011643780232932473),
 ('initial_list_status_f', 0.0012590592139526333),
 ('application_type_Individual', 0.0014454084558789867),
 ('verification_status_Not Verified', 0.0017391813418693705),
 ('verification_status_Verified', 0.0018617270854640192),
 ('pub_rec', 0.0018889433574908515),
 ('initial_list_status_w', 0.0019274359635570286),
 ('home_ownership_MORTGAGE', 0.00193443069732324),
 ('pub_rec_bankruptcies', 0.001992353472110223),
 ('home_ownership_RENT', 0.0022221276045384973),
 ('application_type_Joint App', 0.0023974675978849004),
 ('home_ownership_OWN', 0.0027099661755470273),
 ('num_accts_ever_120_pd', 0.003151854956806326),
 ('tot_coll_amt', 0.0031787778888996685),
 ('delinq_2yrs', 0.004209285536133031),
 ('open_rv_12m', 0.004659163957575057),
 ('next_pymnt_d_May-2019', 0.004836576402052857),
 ('total_cu_tl', 0.005333959490602654),
 ('next_pymnt_d_Apr-2019', 0.005937833190786472),
 ('acc_open_past_24mths', 0.006029835385420927),
 ('total_rec_late_fee', 0.0061211294014324414),
 ('open_il_24m', 0.006219709314207927),
 ('open_il_12m', 0.006380126702785555),
 ('num_tl_op_past_12m', 0.006424849332591853),
 ('issue_d_Feb-2019', 0.006474023725326782),
 ('inq_fi', 0.006543534259359834),
 ('inq_last_6mths', 0.0065844415778603576),
 ('open_act_il', 0.006751026340452478),
 ('percent_bc_gt_75', 0.006793938501804807),
 ('num_bc_sats', 0.006803665104546312),
 ('num_actv_bc_tl', 0.007098142977214213),
 ('open_rv_24m', 0.007446713412162036),
 ('pct_tl_nvr_dlq', 0.007538707734129439),
 ('mort_acc', 0.007705215066707449),
 ('open_acc_6m', 0.007869019215354729),
 ('num_sats', 0.008123438090367857),
 ('mo_sin_rcnt_rev_tl_op', 0.008178149372489282),
 ('num_rev_tl_bal_gt_0', 0.008292001924978313),
 ('mo_sin_rcnt_tl', 0.00859412285704626),
 ('num_bc_tl', 0.008757049235230003),
 ('open_acc', 0.009007580598437405),
 ('num_op_rev_tl', 0.009377259904902),
 ('num_actv_rev_tl', 0.00981375468370214),
 ('total_acc', 0.010175403007785095),
 ('inq_last_12m', 0.01074904123996373),
 ('issue_d_Mar-2019', 0.010822854561763892),
 ('total_il_high_credit_limit', 0.011037937313436483),
 ('num_il_tl', 0.011094800604110309),
 ('bc_util', 0.01169719814209769),
 ('all_util', 0.012103750577541724),
 ('mths_since_recent_bc', 0.012151491440483587),
 ('bc_open_to_buy', 0.012169969000759371),
 ('total_bal_il', 0.012825876753115723),
 ('mo_sin_old_rev_tl_op', 0.012875904906917023),
 ('il_util', 0.012888053378463604),
 ('num_rev_accts', 0.013001856470025549),
 ('total_bc_limit', 0.013227716553050339),
 ('out_prncp', 0.013656626628958687),
 ('total_rev_hi_lim', 0.013990110398200837),
 ('tot_cur_bal', 0.014625066175683005),
 ('loan_amnt', 0.01468309426875756),
 ('revol_bal', 0.014703239004269631),
 ('mo_sin_old_il_acct', 0.015070438283820948),
 ('total_bal_ex_mort', 0.01526591487383901),
 ('avg_cur_bal', 0.015401559992993542),
 ('annual_inc', 0.015475446292510924),
 ('mths_since_rcnt_il', 0.015492733255882948),
 ('tot_hi_cred_lim', 0.01557059484920598),
 ('out_prncp_inv', 0.016390592108821798),
 ('max_bal_bc', 0.016833718489541634),
 ('mths_since_recent_inq', 0.01776579992633344),
 ('dti', 0.018962362417771376),
 ('issue_d_Jan-2019', 0.019313511337999086),
 ('installment', 0.019322889263067498),
 ('int_rate', 0.0273665060886078),
 ('last_pymnt_amnt', 0.0490242930565887),
 ('total_pymnt_inv', 0.05139054408070708),
 ('total_pymnt', 0.057505829983171386),
 ('total_rec_int', 0.06306316852347478),
 ('total_rec_prncp', 0.07717868497990578)]

In [2]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE

### Easy Ensemble AdaBoost Classifier

In [51]:
# Train the EasyEnsembleClassifier
# YOUR CODE HERE

from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier (random_state=1, n_estimators=100).fit(X_train, y_train)

In [52]:
y_pred = eec.predict(X_test)

In [53]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9320108665450269

In [54]:
# Display the confusion matrix
# YOUR CODE HERE

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[   93,     8],
       [  971, 16133]], dtype=int64)

In [55]:
# Print the imbalanced classification report
# YOUR CODE HERE
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205